---
driver:
  name: vagrant
  network:
    - ['private_network', {ip: '33.33.33.33'}]
    - ['forwarded_port', {guest: 9876, host: 9876}]
provisioner:
  name: chef_zero
  require_chef_omnibus: true
platforms:
- name: ubuntu-14.04
suites:
- name: default
  run_list:
    - "recipe[debugbook::default]"
